/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'

const SignupLazyRouteImport = createFileRoute('/signup')()
const LoginLazyRouteImport = createFileRoute('/login')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const StaffIndexLazyRouteImport = createFileRoute('/staff/')()
const CustomerInterfaceIndexLazyRouteImport = createFileRoute(
  '/customer-interface/',
)()
const ChefInterfaceIndexLazyRouteImport = createFileRoute('/chef-interface/')()
const AdminInterfaceIndexLazyRouteImport =
  createFileRoute('/admin-interface/')()
const StaffScheduleLazyRouteImport = createFileRoute('/staff/schedule')()
const StaffReviewsLazyRouteImport = createFileRoute('/staff/reviews')()
const StaffRefundLazyRouteImport = createFileRoute('/staff/refund')()
const StaffMyInfoLazyRouteImport = createFileRoute('/staff/my-info')()
const StaffMenuLazyRouteImport = createFileRoute('/staff/menu')()
const StaffDeliveriesLazyRouteImport = createFileRoute('/staff/deliveries')()
const CustomerInterfacePaymentLazyRouteImport = createFileRoute(
  '/customer-interface/payment',
)()
const CustomerInterfaceOrderLazyRouteImport = createFileRoute(
  '/customer-interface/order',
)()
const CustomerInterfaceMyInfoLazyRouteImport = createFileRoute(
  '/customer-interface/my-info',
)()
const CustomerInterfaceHomeLazyRouteImport = createFileRoute(
  '/customer-interface/home',
)()
const CustomerInterfaceCartLazyRouteImport = createFileRoute(
  '/customer-interface/cart',
)()
const ChefInterfaceMyInfoLazyRouteImport = createFileRoute(
  '/chef-interface/my-info',
)()
const AdminInterfaceScheduleLazyRouteImport = createFileRoute(
  '/admin-interface/schedule',
)()
const AdminInterfaceSalesLazyRouteImport = createFileRoute(
  '/admin-interface/sales',
)()
const AdminInterfaceReviewsLazyRouteImport = createFileRoute(
  '/admin-interface/reviews',
)()
const AdminInterfaceRefundLazyRouteImport = createFileRoute(
  '/admin-interface/refund',
)()
const AdminInterfaceOrdersLazyRouteImport = createFileRoute(
  '/admin-interface/orders',
)()
const AdminInterfaceMenuLazyRouteImport = createFileRoute(
  '/admin-interface/menu',
)()
const CustomerInterfaceFeedbackIndexLazyRouteImport = createFileRoute(
  '/customer-interface/feedback/',
)()
const AdminInterfaceEmployeeIndexLazyRouteImport = createFileRoute(
  '/admin-interface/employee/',
)()
const StaffLayoutStaffLayoutLazyRouteImport = createFileRoute(
  '/staff/layout/staff-layout',
)()
const CustomerInterfaceSpecificOrderOrderIdLazyRouteImport = createFileRoute(
  '/customer-interface/specific-order/$orderId',
)()
const CustomerInterfaceFeedbackFeedbackIdLazyRouteImport = createFileRoute(
  '/customer-interface/feedback/$feedbackId',
)()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StaffIndexLazyRoute = StaffIndexLazyRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/staff/index.lazy').then((d) => d.Route))
const CustomerInterfaceIndexLazyRoute =
  CustomerInterfaceIndexLazyRouteImport.update({
    id: '/customer-interface/',
    path: '/customer-interface/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/index.lazy').then((d) => d.Route),
  )
const ChefInterfaceIndexLazyRoute = ChefInterfaceIndexLazyRouteImport.update({
  id: '/chef-interface/',
  path: '/chef-interface/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chef-interface/index.lazy').then((d) => d.Route),
)
const AdminInterfaceIndexLazyRoute = AdminInterfaceIndexLazyRouteImport.update({
  id: '/admin-interface/',
  path: '/admin-interface/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin-interface/index.lazy').then((d) => d.Route),
)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffScheduleLazyRoute = StaffScheduleLazyRouteImport.update({
  id: '/staff/schedule',
  path: '/staff/schedule',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/staff/schedule.lazy').then((d) => d.Route),
)
const StaffReviewsLazyRoute = StaffReviewsLazyRouteImport.update({
  id: '/staff/reviews',
  path: '/staff/reviews',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/staff/reviews.lazy').then((d) => d.Route))
const StaffRefundLazyRoute = StaffRefundLazyRouteImport.update({
  id: '/staff/refund',
  path: '/staff/refund',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/staff/refund.lazy').then((d) => d.Route))
const StaffMyInfoLazyRoute = StaffMyInfoLazyRouteImport.update({
  id: '/staff/my-info',
  path: '/staff/my-info',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/staff/my-info.lazy').then((d) => d.Route))
const StaffMenuLazyRoute = StaffMenuLazyRouteImport.update({
  id: '/staff/menu',
  path: '/staff/menu',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/staff/menu.lazy').then((d) => d.Route))
const StaffDeliveriesLazyRoute = StaffDeliveriesLazyRouteImport.update({
  id: '/staff/deliveries',
  path: '/staff/deliveries',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/staff/deliveries.lazy').then((d) => d.Route),
)
const CustomerInterfacePaymentLazyRoute =
  CustomerInterfacePaymentLazyRouteImport.update({
    id: '/customer-interface/payment',
    path: '/customer-interface/payment',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/payment.lazy').then((d) => d.Route),
  )
const CustomerInterfaceOrderLazyRoute =
  CustomerInterfaceOrderLazyRouteImport.update({
    id: '/customer-interface/order',
    path: '/customer-interface/order',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/order.lazy').then((d) => d.Route),
  )
const CustomerInterfaceMyInfoLazyRoute =
  CustomerInterfaceMyInfoLazyRouteImport.update({
    id: '/customer-interface/my-info',
    path: '/customer-interface/my-info',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/my-info.lazy').then((d) => d.Route),
  )
const CustomerInterfaceHomeLazyRoute =
  CustomerInterfaceHomeLazyRouteImport.update({
    id: '/customer-interface/home',
    path: '/customer-interface/home',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/home.lazy').then((d) => d.Route),
  )
const CustomerInterfaceCartLazyRoute =
  CustomerInterfaceCartLazyRouteImport.update({
    id: '/customer-interface/cart',
    path: '/customer-interface/cart',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/cart.lazy').then((d) => d.Route),
  )
const ChefInterfaceMyInfoLazyRoute = ChefInterfaceMyInfoLazyRouteImport.update({
  id: '/chef-interface/my-info',
  path: '/chef-interface/my-info',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chef-interface/my-info.lazy').then((d) => d.Route),
)
const AdminInterfaceScheduleLazyRoute =
  AdminInterfaceScheduleLazyRouteImport.update({
    id: '/admin-interface/schedule',
    path: '/admin-interface/schedule',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin-interface/schedule.lazy').then((d) => d.Route),
  )
const AdminInterfaceSalesLazyRoute = AdminInterfaceSalesLazyRouteImport.update({
  id: '/admin-interface/sales',
  path: '/admin-interface/sales',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin-interface/sales.lazy').then((d) => d.Route),
)
const AdminInterfaceReviewsLazyRoute =
  AdminInterfaceReviewsLazyRouteImport.update({
    id: '/admin-interface/reviews',
    path: '/admin-interface/reviews',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin-interface/reviews.lazy').then((d) => d.Route),
  )
const AdminInterfaceRefundLazyRoute =
  AdminInterfaceRefundLazyRouteImport.update({
    id: '/admin-interface/refund',
    path: '/admin-interface/refund',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin-interface/refund.lazy').then((d) => d.Route),
  )
const AdminInterfaceOrdersLazyRoute =
  AdminInterfaceOrdersLazyRouteImport.update({
    id: '/admin-interface/orders',
    path: '/admin-interface/orders',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin-interface/orders.lazy').then((d) => d.Route),
  )
const AdminInterfaceMenuLazyRoute = AdminInterfaceMenuLazyRouteImport.update({
  id: '/admin-interface/menu',
  path: '/admin-interface/menu',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin-interface/menu.lazy').then((d) => d.Route),
)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerInterfaceFeedbackIndexLazyRoute =
  CustomerInterfaceFeedbackIndexLazyRouteImport.update({
    id: '/customer-interface/feedback/',
    path: '/customer-interface/feedback/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/feedback/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminInterfaceEmployeeIndexLazyRoute =
  AdminInterfaceEmployeeIndexLazyRouteImport.update({
    id: '/admin-interface/employee/',
    path: '/admin-interface/employee/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/admin-interface/employee/index.lazy').then((d) => d.Route),
  )
const StaffLayoutStaffLayoutLazyRoute =
  StaffLayoutStaffLayoutLazyRouteImport.update({
    id: '/staff/layout/staff-layout',
    path: '/staff/layout/staff-layout',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/staff/layout/staff-layout.lazy').then((d) => d.Route),
  )
const CustomerInterfaceSpecificOrderOrderIdLazyRoute =
  CustomerInterfaceSpecificOrderOrderIdLazyRouteImport.update({
    id: '/customer-interface/specific-order/$orderId',
    path: '/customer-interface/specific-order/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/specific-order/$orderId.lazy').then(
      (d) => d.Route,
    ),
  )
const CustomerInterfaceFeedbackFeedbackIdLazyRoute =
  CustomerInterfaceFeedbackFeedbackIdLazyRouteImport.update({
    id: '/customer-interface/feedback/$feedbackId',
    path: '/customer-interface/feedback/$feedbackId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/customer-interface/feedback/$feedbackId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin-interface/menu': typeof AdminInterfaceMenuLazyRoute
  '/admin-interface/orders': typeof AdminInterfaceOrdersLazyRoute
  '/admin-interface/refund': typeof AdminInterfaceRefundLazyRoute
  '/admin-interface/reviews': typeof AdminInterfaceReviewsLazyRoute
  '/admin-interface/sales': typeof AdminInterfaceSalesLazyRoute
  '/admin-interface/schedule': typeof AdminInterfaceScheduleLazyRoute
  '/chef-interface/my-info': typeof ChefInterfaceMyInfoLazyRoute
  '/customer-interface/cart': typeof CustomerInterfaceCartLazyRoute
  '/customer-interface/home': typeof CustomerInterfaceHomeLazyRoute
  '/customer-interface/my-info': typeof CustomerInterfaceMyInfoLazyRoute
  '/customer-interface/order': typeof CustomerInterfaceOrderLazyRoute
  '/customer-interface/payment': typeof CustomerInterfacePaymentLazyRoute
  '/staff/deliveries': typeof StaffDeliveriesLazyRoute
  '/staff/menu': typeof StaffMenuLazyRoute
  '/staff/my-info': typeof StaffMyInfoLazyRoute
  '/staff/refund': typeof StaffRefundLazyRoute
  '/staff/reviews': typeof StaffReviewsLazyRoute
  '/staff/schedule': typeof StaffScheduleLazyRoute
  '/posts': typeof PostsIndexRoute
  '/admin-interface': typeof AdminInterfaceIndexLazyRoute
  '/chef-interface': typeof ChefInterfaceIndexLazyRoute
  '/customer-interface': typeof CustomerInterfaceIndexLazyRoute
  '/staff': typeof StaffIndexLazyRoute
  '/customer-interface/feedback/$feedbackId': typeof CustomerInterfaceFeedbackFeedbackIdLazyRoute
  '/customer-interface/specific-order/$orderId': typeof CustomerInterfaceSpecificOrderOrderIdLazyRoute
  '/staff/layout/staff-layout': typeof StaffLayoutStaffLayoutLazyRoute
  '/admin-interface/employee': typeof AdminInterfaceEmployeeIndexLazyRoute
  '/customer-interface/feedback': typeof CustomerInterfaceFeedbackIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin-interface/menu': typeof AdminInterfaceMenuLazyRoute
  '/admin-interface/orders': typeof AdminInterfaceOrdersLazyRoute
  '/admin-interface/refund': typeof AdminInterfaceRefundLazyRoute
  '/admin-interface/reviews': typeof AdminInterfaceReviewsLazyRoute
  '/admin-interface/sales': typeof AdminInterfaceSalesLazyRoute
  '/admin-interface/schedule': typeof AdminInterfaceScheduleLazyRoute
  '/chef-interface/my-info': typeof ChefInterfaceMyInfoLazyRoute
  '/customer-interface/cart': typeof CustomerInterfaceCartLazyRoute
  '/customer-interface/home': typeof CustomerInterfaceHomeLazyRoute
  '/customer-interface/my-info': typeof CustomerInterfaceMyInfoLazyRoute
  '/customer-interface/order': typeof CustomerInterfaceOrderLazyRoute
  '/customer-interface/payment': typeof CustomerInterfacePaymentLazyRoute
  '/staff/deliveries': typeof StaffDeliveriesLazyRoute
  '/staff/menu': typeof StaffMenuLazyRoute
  '/staff/my-info': typeof StaffMyInfoLazyRoute
  '/staff/refund': typeof StaffRefundLazyRoute
  '/staff/reviews': typeof StaffReviewsLazyRoute
  '/staff/schedule': typeof StaffScheduleLazyRoute
  '/posts': typeof PostsIndexRoute
  '/admin-interface': typeof AdminInterfaceIndexLazyRoute
  '/chef-interface': typeof ChefInterfaceIndexLazyRoute
  '/customer-interface': typeof CustomerInterfaceIndexLazyRoute
  '/staff': typeof StaffIndexLazyRoute
  '/customer-interface/feedback/$feedbackId': typeof CustomerInterfaceFeedbackFeedbackIdLazyRoute
  '/customer-interface/specific-order/$orderId': typeof CustomerInterfaceSpecificOrderOrderIdLazyRoute
  '/staff/layout/staff-layout': typeof StaffLayoutStaffLayoutLazyRoute
  '/admin-interface/employee': typeof AdminInterfaceEmployeeIndexLazyRoute
  '/customer-interface/feedback': typeof CustomerInterfaceFeedbackIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin-interface/menu': typeof AdminInterfaceMenuLazyRoute
  '/admin-interface/orders': typeof AdminInterfaceOrdersLazyRoute
  '/admin-interface/refund': typeof AdminInterfaceRefundLazyRoute
  '/admin-interface/reviews': typeof AdminInterfaceReviewsLazyRoute
  '/admin-interface/sales': typeof AdminInterfaceSalesLazyRoute
  '/admin-interface/schedule': typeof AdminInterfaceScheduleLazyRoute
  '/chef-interface/my-info': typeof ChefInterfaceMyInfoLazyRoute
  '/customer-interface/cart': typeof CustomerInterfaceCartLazyRoute
  '/customer-interface/home': typeof CustomerInterfaceHomeLazyRoute
  '/customer-interface/my-info': typeof CustomerInterfaceMyInfoLazyRoute
  '/customer-interface/order': typeof CustomerInterfaceOrderLazyRoute
  '/customer-interface/payment': typeof CustomerInterfacePaymentLazyRoute
  '/staff/deliveries': typeof StaffDeliveriesLazyRoute
  '/staff/menu': typeof StaffMenuLazyRoute
  '/staff/my-info': typeof StaffMyInfoLazyRoute
  '/staff/refund': typeof StaffRefundLazyRoute
  '/staff/reviews': typeof StaffReviewsLazyRoute
  '/staff/schedule': typeof StaffScheduleLazyRoute
  '/posts/': typeof PostsIndexRoute
  '/admin-interface/': typeof AdminInterfaceIndexLazyRoute
  '/chef-interface/': typeof ChefInterfaceIndexLazyRoute
  '/customer-interface/': typeof CustomerInterfaceIndexLazyRoute
  '/staff/': typeof StaffIndexLazyRoute
  '/customer-interface/feedback/$feedbackId': typeof CustomerInterfaceFeedbackFeedbackIdLazyRoute
  '/customer-interface/specific-order/$orderId': typeof CustomerInterfaceSpecificOrderOrderIdLazyRoute
  '/staff/layout/staff-layout': typeof StaffLayoutStaffLayoutLazyRoute
  '/admin-interface/employee/': typeof AdminInterfaceEmployeeIndexLazyRoute
  '/customer-interface/feedback/': typeof CustomerInterfaceFeedbackIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/posts/$postId'
    | '/admin-interface/menu'
    | '/admin-interface/orders'
    | '/admin-interface/refund'
    | '/admin-interface/reviews'
    | '/admin-interface/sales'
    | '/admin-interface/schedule'
    | '/chef-interface/my-info'
    | '/customer-interface/cart'
    | '/customer-interface/home'
    | '/customer-interface/my-info'
    | '/customer-interface/order'
    | '/customer-interface/payment'
    | '/staff/deliveries'
    | '/staff/menu'
    | '/staff/my-info'
    | '/staff/refund'
    | '/staff/reviews'
    | '/staff/schedule'
    | '/posts'
    | '/admin-interface'
    | '/chef-interface'
    | '/customer-interface'
    | '/staff'
    | '/customer-interface/feedback/$feedbackId'
    | '/customer-interface/specific-order/$orderId'
    | '/staff/layout/staff-layout'
    | '/admin-interface/employee'
    | '/customer-interface/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/posts/$postId'
    | '/admin-interface/menu'
    | '/admin-interface/orders'
    | '/admin-interface/refund'
    | '/admin-interface/reviews'
    | '/admin-interface/sales'
    | '/admin-interface/schedule'
    | '/chef-interface/my-info'
    | '/customer-interface/cart'
    | '/customer-interface/home'
    | '/customer-interface/my-info'
    | '/customer-interface/order'
    | '/customer-interface/payment'
    | '/staff/deliveries'
    | '/staff/menu'
    | '/staff/my-info'
    | '/staff/refund'
    | '/staff/reviews'
    | '/staff/schedule'
    | '/posts'
    | '/admin-interface'
    | '/chef-interface'
    | '/customer-interface'
    | '/staff'
    | '/customer-interface/feedback/$feedbackId'
    | '/customer-interface/specific-order/$orderId'
    | '/staff/layout/staff-layout'
    | '/admin-interface/employee'
    | '/customer-interface/feedback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/posts/$postId'
    | '/admin-interface/menu'
    | '/admin-interface/orders'
    | '/admin-interface/refund'
    | '/admin-interface/reviews'
    | '/admin-interface/sales'
    | '/admin-interface/schedule'
    | '/chef-interface/my-info'
    | '/customer-interface/cart'
    | '/customer-interface/home'
    | '/customer-interface/my-info'
    | '/customer-interface/order'
    | '/customer-interface/payment'
    | '/staff/deliveries'
    | '/staff/menu'
    | '/staff/my-info'
    | '/staff/refund'
    | '/staff/reviews'
    | '/staff/schedule'
    | '/posts/'
    | '/admin-interface/'
    | '/chef-interface/'
    | '/customer-interface/'
    | '/staff/'
    | '/customer-interface/feedback/$feedbackId'
    | '/customer-interface/specific-order/$orderId'
    | '/staff/layout/staff-layout'
    | '/admin-interface/employee/'
    | '/customer-interface/feedback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  AdminInterfaceMenuLazyRoute: typeof AdminInterfaceMenuLazyRoute
  AdminInterfaceOrdersLazyRoute: typeof AdminInterfaceOrdersLazyRoute
  AdminInterfaceRefundLazyRoute: typeof AdminInterfaceRefundLazyRoute
  AdminInterfaceReviewsLazyRoute: typeof AdminInterfaceReviewsLazyRoute
  AdminInterfaceSalesLazyRoute: typeof AdminInterfaceSalesLazyRoute
  AdminInterfaceScheduleLazyRoute: typeof AdminInterfaceScheduleLazyRoute
  ChefInterfaceMyInfoLazyRoute: typeof ChefInterfaceMyInfoLazyRoute
  CustomerInterfaceCartLazyRoute: typeof CustomerInterfaceCartLazyRoute
  CustomerInterfaceHomeLazyRoute: typeof CustomerInterfaceHomeLazyRoute
  CustomerInterfaceMyInfoLazyRoute: typeof CustomerInterfaceMyInfoLazyRoute
  CustomerInterfaceOrderLazyRoute: typeof CustomerInterfaceOrderLazyRoute
  CustomerInterfacePaymentLazyRoute: typeof CustomerInterfacePaymentLazyRoute
  StaffDeliveriesLazyRoute: typeof StaffDeliveriesLazyRoute
  StaffMenuLazyRoute: typeof StaffMenuLazyRoute
  StaffMyInfoLazyRoute: typeof StaffMyInfoLazyRoute
  StaffRefundLazyRoute: typeof StaffRefundLazyRoute
  StaffReviewsLazyRoute: typeof StaffReviewsLazyRoute
  StaffScheduleLazyRoute: typeof StaffScheduleLazyRoute
  PostsIndexRoute: typeof PostsIndexRoute
  AdminInterfaceIndexLazyRoute: typeof AdminInterfaceIndexLazyRoute
  ChefInterfaceIndexLazyRoute: typeof ChefInterfaceIndexLazyRoute
  CustomerInterfaceIndexLazyRoute: typeof CustomerInterfaceIndexLazyRoute
  StaffIndexLazyRoute: typeof StaffIndexLazyRoute
  CustomerInterfaceFeedbackFeedbackIdLazyRoute: typeof CustomerInterfaceFeedbackFeedbackIdLazyRoute
  CustomerInterfaceSpecificOrderOrderIdLazyRoute: typeof CustomerInterfaceSpecificOrderOrderIdLazyRoute
  StaffLayoutStaffLayoutLazyRoute: typeof StaffLayoutStaffLayoutLazyRoute
  AdminInterfaceEmployeeIndexLazyRoute: typeof AdminInterfaceEmployeeIndexLazyRoute
  CustomerInterfaceFeedbackIndexLazyRoute: typeof CustomerInterfaceFeedbackIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/': {
      id: '/customer-interface/'
      path: '/customer-interface'
      fullPath: '/customer-interface'
      preLoaderRoute: typeof CustomerInterfaceIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-interface/': {
      id: '/chef-interface/'
      path: '/chef-interface'
      fullPath: '/chef-interface'
      preLoaderRoute: typeof ChefInterfaceIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/': {
      id: '/admin-interface/'
      path: '/admin-interface'
      fullPath: '/admin-interface'
      preLoaderRoute: typeof AdminInterfaceIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/schedule': {
      id: '/staff/schedule'
      path: '/staff/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof StaffScheduleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reviews': {
      id: '/staff/reviews'
      path: '/staff/reviews'
      fullPath: '/staff/reviews'
      preLoaderRoute: typeof StaffReviewsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/refund': {
      id: '/staff/refund'
      path: '/staff/refund'
      fullPath: '/staff/refund'
      preLoaderRoute: typeof StaffRefundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/my-info': {
      id: '/staff/my-info'
      path: '/staff/my-info'
      fullPath: '/staff/my-info'
      preLoaderRoute: typeof StaffMyInfoLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/menu': {
      id: '/staff/menu'
      path: '/staff/menu'
      fullPath: '/staff/menu'
      preLoaderRoute: typeof StaffMenuLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/deliveries': {
      id: '/staff/deliveries'
      path: '/staff/deliveries'
      fullPath: '/staff/deliveries'
      preLoaderRoute: typeof StaffDeliveriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/payment': {
      id: '/customer-interface/payment'
      path: '/customer-interface/payment'
      fullPath: '/customer-interface/payment'
      preLoaderRoute: typeof CustomerInterfacePaymentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/order': {
      id: '/customer-interface/order'
      path: '/customer-interface/order'
      fullPath: '/customer-interface/order'
      preLoaderRoute: typeof CustomerInterfaceOrderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/my-info': {
      id: '/customer-interface/my-info'
      path: '/customer-interface/my-info'
      fullPath: '/customer-interface/my-info'
      preLoaderRoute: typeof CustomerInterfaceMyInfoLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/home': {
      id: '/customer-interface/home'
      path: '/customer-interface/home'
      fullPath: '/customer-interface/home'
      preLoaderRoute: typeof CustomerInterfaceHomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/cart': {
      id: '/customer-interface/cart'
      path: '/customer-interface/cart'
      fullPath: '/customer-interface/cart'
      preLoaderRoute: typeof CustomerInterfaceCartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-interface/my-info': {
      id: '/chef-interface/my-info'
      path: '/chef-interface/my-info'
      fullPath: '/chef-interface/my-info'
      preLoaderRoute: typeof ChefInterfaceMyInfoLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/schedule': {
      id: '/admin-interface/schedule'
      path: '/admin-interface/schedule'
      fullPath: '/admin-interface/schedule'
      preLoaderRoute: typeof AdminInterfaceScheduleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/sales': {
      id: '/admin-interface/sales'
      path: '/admin-interface/sales'
      fullPath: '/admin-interface/sales'
      preLoaderRoute: typeof AdminInterfaceSalesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/reviews': {
      id: '/admin-interface/reviews'
      path: '/admin-interface/reviews'
      fullPath: '/admin-interface/reviews'
      preLoaderRoute: typeof AdminInterfaceReviewsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/refund': {
      id: '/admin-interface/refund'
      path: '/admin-interface/refund'
      fullPath: '/admin-interface/refund'
      preLoaderRoute: typeof AdminInterfaceRefundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/orders': {
      id: '/admin-interface/orders'
      path: '/admin-interface/orders'
      fullPath: '/admin-interface/orders'
      preLoaderRoute: typeof AdminInterfaceOrdersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/menu': {
      id: '/admin-interface/menu'
      path: '/admin-interface/menu'
      fullPath: '/admin-interface/menu'
      preLoaderRoute: typeof AdminInterfaceMenuLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/feedback/': {
      id: '/customer-interface/feedback/'
      path: '/customer-interface/feedback'
      fullPath: '/customer-interface/feedback'
      preLoaderRoute: typeof CustomerInterfaceFeedbackIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-interface/employee/': {
      id: '/admin-interface/employee/'
      path: '/admin-interface/employee'
      fullPath: '/admin-interface/employee'
      preLoaderRoute: typeof AdminInterfaceEmployeeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/layout/staff-layout': {
      id: '/staff/layout/staff-layout'
      path: '/staff/layout/staff-layout'
      fullPath: '/staff/layout/staff-layout'
      preLoaderRoute: typeof StaffLayoutStaffLayoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/specific-order/$orderId': {
      id: '/customer-interface/specific-order/$orderId'
      path: '/customer-interface/specific-order/$orderId'
      fullPath: '/customer-interface/specific-order/$orderId'
      preLoaderRoute: typeof CustomerInterfaceSpecificOrderOrderIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-interface/feedback/$feedbackId': {
      id: '/customer-interface/feedback/$feedbackId'
      path: '/customer-interface/feedback/$feedbackId'
      fullPath: '/customer-interface/feedback/$feedbackId'
      preLoaderRoute: typeof CustomerInterfaceFeedbackFeedbackIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  AdminInterfaceMenuLazyRoute: AdminInterfaceMenuLazyRoute,
  AdminInterfaceOrdersLazyRoute: AdminInterfaceOrdersLazyRoute,
  AdminInterfaceRefundLazyRoute: AdminInterfaceRefundLazyRoute,
  AdminInterfaceReviewsLazyRoute: AdminInterfaceReviewsLazyRoute,
  AdminInterfaceSalesLazyRoute: AdminInterfaceSalesLazyRoute,
  AdminInterfaceScheduleLazyRoute: AdminInterfaceScheduleLazyRoute,
  ChefInterfaceMyInfoLazyRoute: ChefInterfaceMyInfoLazyRoute,
  CustomerInterfaceCartLazyRoute: CustomerInterfaceCartLazyRoute,
  CustomerInterfaceHomeLazyRoute: CustomerInterfaceHomeLazyRoute,
  CustomerInterfaceMyInfoLazyRoute: CustomerInterfaceMyInfoLazyRoute,
  CustomerInterfaceOrderLazyRoute: CustomerInterfaceOrderLazyRoute,
  CustomerInterfacePaymentLazyRoute: CustomerInterfacePaymentLazyRoute,
  StaffDeliveriesLazyRoute: StaffDeliveriesLazyRoute,
  StaffMenuLazyRoute: StaffMenuLazyRoute,
  StaffMyInfoLazyRoute: StaffMyInfoLazyRoute,
  StaffRefundLazyRoute: StaffRefundLazyRoute,
  StaffReviewsLazyRoute: StaffReviewsLazyRoute,
  StaffScheduleLazyRoute: StaffScheduleLazyRoute,
  PostsIndexRoute: PostsIndexRoute,
  AdminInterfaceIndexLazyRoute: AdminInterfaceIndexLazyRoute,
  ChefInterfaceIndexLazyRoute: ChefInterfaceIndexLazyRoute,
  CustomerInterfaceIndexLazyRoute: CustomerInterfaceIndexLazyRoute,
  StaffIndexLazyRoute: StaffIndexLazyRoute,
  CustomerInterfaceFeedbackFeedbackIdLazyRoute:
    CustomerInterfaceFeedbackFeedbackIdLazyRoute,
  CustomerInterfaceSpecificOrderOrderIdLazyRoute:
    CustomerInterfaceSpecificOrderOrderIdLazyRoute,
  StaffLayoutStaffLayoutLazyRoute: StaffLayoutStaffLayoutLazyRoute,
  AdminInterfaceEmployeeIndexLazyRoute: AdminInterfaceEmployeeIndexLazyRoute,
  CustomerInterfaceFeedbackIndexLazyRoute:
    CustomerInterfaceFeedbackIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
